# Change these first
owner: Gwangtori # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Introduce Page
    url: https://me.gwangtori.com
  - name: onemindwiki
    url: https://onemind.gwto.cc
  - name: IT blog
    url: https://it.gwangtori.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gwto.cc
  # baseUrl: /Upptime
  logoUrl: https://file.gwto.cc/symbol.svg
  name: 서비스 모니터링
  introTitle: "**서비스 모니터링**"
  introMessage: "광토리가 운영하는 서비스의 상태를 확인할 수 있는 공간이에요."
  navbar:
    - title: Status
      href: /
    - title: me
      href: https://me.gwangtori.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
